version: '3.5'

services:
  db:
    image: postgres:12.2
    environment:
      POSTGRES_DB: judge0
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: judge0
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:6.0.5
    restart: always

  api:
    image: judge0/judge0:latest
    environment:
      - DATABASE_URL=postgresql://judge0:judge0@db:5432/judge0
      - REDIS_URL=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=secret
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - PORT=2358
    ports:
      - "2358:2358"
    depends_on:
      - db
      - redis
    restart: always

volumes:
  db-data: